substitutions:
  _SA_EMAIL: "tf-runner@$PROJECT_ID.iam.gserviceaccount.com"

steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Auth (impersonate tf-runner)'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud config set project $PROJECT_ID
        gcloud auth application-default set-quota-project $PROJECT_ID
        gcloud auth print-identity-token >/dev/null
        gcloud auth impersonate-service-account ${_SA_EMAIL} --quiet

  - name: 'hashicorp/terraform:1.8'
    id: 'Terraform Init'
    entrypoint: sh
    args:
      - -c
      - |
        terraform init -upgrade

  - name: 'hashicorp/terraform:1.8'
    id: 'Terraform Plan'
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -out=tfplan

  - name: 'hashicorp/terraform:1.8'
    id: 'Terraform Apply'
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve tfplan

options:
  logging: CLOUD_LOGGING_ONLY
